name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    environment:
      name: WingsMagApi
    runs-on: ubuntu-latest

    steps:
      - name: Restart on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd wings-map-api
            git pull origin main   # 👈 pull the latest changes
            sudo systemctl restart wingsmag
            sudo systemctl status wingsmag --no-pager -l
